### ISSUE TITLE
Android Oreo 适配问题，启动崩溃

### ISSUE THREAD

**Issue by TinloneX** [nanchen2251/AiYaGirl#12]
配置v26 style中此处值为false
<item name="android:windowIsTranslucent">false</item>
解决Oreo报 Caused by: java.lang.IllegalStateException: Only fullscreen opaque activities can request orientation问题

**Comment by nanchen2251** [comment]
请直接 PR 代码~

**Comment by TinloneX** [comment]
噗，xml被github干掉了
`<item `name="android:windowIsTranslucent">false</item>`

**Comment by TinloneX** [comment]
没有用MD格式，xml被当作HTML节点干掉了，以下是内容
`<item name="android:windowIsTranslucent">false</item> `
