### ISSUE TITLE
关于项目参考问题

### ISSUE THREAD

**Issue by youlookwhat** [nanchen2251/AiYaGirl#5]
作者你好，我是[《云阅》](https://github.com/youlookwhat/CloudReader)开源项目的作者。看到您的项目知道您废了很多心血，也看到演示效果图里的《云阅》，进入项目时我看到了熟悉的页面，还以为是我的，后来得知是复用了一部分页面。
开源不易，希望作者写上参考项目，非常感谢！

**Comment by nanchen2251** [comment]
OK，非常抱歉，这里忘了添加上Your url，马上添加。感谢你为开源社区做出的伟大贡献。抱歉，才看到。
