### ISSUE TITLE
关于图片下载，可以直接拿到bitmap，不用在Presenter里面转

### ISSUE THREAD

**Issue by yechaoa** [nanchen2251/AiYaGirl#6]
`Glide.with(Utils.getContext())
                .load(mImageUrl)
                .asBitmap()
                .diskCacheStrategy(DiskCacheStrategy.ALL)
                .into(new SimpleTarget<Bitmap>() {
                    @Override
                    public void onResourceReady(Bitmap bitmap, GlideAnimation<? super Bitmap> glideAnimation) {
                        hideProgress();
                        mBitmap=bitmap;
                        mImgView.setImageBitmap(bitmap);
                    }
                });`

` mPresenter.saveGirl(mImageUrl, mBitmap, mImageTitle);`

**Comment by nanchen2251** [comment]
非常nice的建议，欢迎直接提交代码，我会直接merge处理。
