### ISSUE TITLE
"问题反馈"页面，QQ方式需要加一层判断，如果没安装qq就Crash了

### ISSUE THREAD

**Issue by yechaoa** [nanchen2251/AiYaGirl#7]
> case R.id.tv_qq:
                if (isQQClientAvailable()) {
                    String url = "mqqwpa://im/chat?chat_type=wpa&uin=503233512";
                    startActivity(new Intent(Intent.ACTION_VIEW, Uri.parse(url)));
                } else
                    Toasty.error(this, "当前设备未安装QQ").show();
                break;

> /**
     * 判断qq是否可用
     */
    public static boolean isQQClientAvailable() {
        final PackageManager packageManager = Utils.getContext().getPackageManager();
        List<PackageInfo> packageInfo = packageManager.getInstalledPackages(0);
        if (packageInfo != null) {
            for (int i = 0; i < packageInfo.size(); i++) {
                String pn = packageInfo.get(i).packageName;
                if (pn.equals("com.tencent.mobileqq")) {
                    return true;
                }
            }
        }
        return false;
    }

**Comment by nanchen2251** [comment]
非常非常nice的建议，感谢提出，希望可以直接pull代码给我，我会直接进行检查Merge处理。Thx
